[package]
name = "vsock-exporter"
version = "0.1.0"
authors = ["James O. D. Hunt <james.o.hunt@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# These three are tightly coupled - we can't bump nix/libc unless it's
# compatible with vsock.
nix = "0.17.0"
libc = "0.2.69"
vsock = "0.2.0"

opentelemetry = { version = "0.6.0", features=["serialize"] }
serde = { version = "1.0.110", features = ["derive"] }
bincode = "1.3.1"
byteorder = "1.3.4"
slog = { version = "2.5.2", features = ["dynamic-keys", "max_level_trace", "release_max_level_info"] }
